/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as R500IndexRouteImport } from "./routes/500/index";
import { Route as ApiChatIndexRouteImport } from "./routes/api/chat/index";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const R500IndexRoute = R500IndexRouteImport.update({
  id: "/500/",
  path: "/500/",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiChatIndexRoute = ApiChatIndexRouteImport.update({
  id: "/api/chat/",
  path: "/api/chat/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/500/": typeof R500IndexRoute;
  "/api/chat/": typeof ApiChatIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/500": typeof R500IndexRoute;
  "/api/chat": typeof ApiChatIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/500/": typeof R500IndexRoute;
  "/api/chat/": typeof ApiChatIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/500/" | "/api/chat/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/500" | "/api/chat";
  id: "__root__" | "/" | "/500/" | "/api/chat/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  R500IndexRoute: typeof R500IndexRoute;
  ApiChatIndexRoute: typeof ApiChatIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/500/": {
      id: "/500/";
      path: "/500";
      fullPath: "/500/";
      preLoaderRoute: typeof R500IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/chat/": {
      id: "/api/chat/";
      path: "/api/chat";
      fullPath: "/api/chat/";
      preLoaderRoute: typeof ApiChatIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R500IndexRoute: R500IndexRoute,
  ApiChatIndexRoute: ApiChatIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.ts";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
